### ISSUE TITLE
your api key

### ISSUE THREAD

**Issue by braingineer** [agermanidis/autosub#1]
does it matter that it's in the constants?  Can it be used maliciously?  

Just thought I'd check =)

**Comment by agermanidis** [comment]
Not quite mine :) It's hard-coded on Chromium. 

https://www.google.com/search?q=%22AIzaSyBOti4mM-6x9WDnZIjIeyEU21OpBXqWBgw%22&oq=%22AIzaSyBOti4mM-6x9WDnZIjIeyEU21OpBXqWBgw%22&aqs=chrome..69i57.551j0j4&sourceid=chrome&es_sm=91&ie=UTF-8

Thanks for letting me know though!

**Comment by braingineer** [comment]
No worries!  I had read a while back that people were leaving their EC2 API keys on their github commits and some malicious people wrote bots to mine github for them, then use them to do nefarious things.
