### ISSUE TITLE
Does AutoSub support Chinese?

### ISSUE THREAD

**Issue by tableaumichael** [agermanidis/autosub#101]
Autosub support English, Spanish and Japanese videos. I see AutoSub_English.bat, AutoSub_Spanish.bat, AutoSub_Japanese.bat in the package.

Does it support Chinese?

**Comment by SFNasty** [comment]
yes

**Comment by tableaumichael** [comment]
How? 

there is no such choice which records the voice with Chinese.
![capture](https://user-images.githubusercontent.com/42328562/45555388-aad1f080-b806-11e8-89c1-0c1f8e2c1309.JPG)

**Comment by tableaumichael** [comment]
The video is spoken in Chinese. I want to extract the voice to a srt file with Chinese text.
