### ISSUE TITLE
Performing speech recognition is not running

### ISSUE THREAD

**Issue by fxbabys** [agermanidis/autosub#107]
I code the `autosub -S en -D en ...` and it shows the `Converting speech regions to FLAC files` with 100% quickly, but when showing the `Performing speech recognition` it just stops at this and not running with always 0% unless I canceling transcription :(

**Comment by fxbabys** [comment]
In the beginning, I think it might be a global proxy's problem for google translate, but accidentally it starts after many minutes...I think it will work. Thank you for providing this nice service.

**Comment by 90youyueo** [comment]
Alright....I'm waiting~

**Comment by mgsweet** [comment]
It is so weird that it worked till yesterday but suddenly face the same problem as fxbabys mentioned.
