### ISSUE TITLE
PicklingError

### ISSUE THREAD

**Issue by ddavout** [agermanidis/autosub#12]
Thanks for this amazing tool .. I try it on with fr as a source and destination language without any issue.
but with the very same video

autosub -F srt -S fr-FR -D en  'fun-sd(0).mp4' 

Converting speech regions to FLAC files: 100% |###########################################| Time: 0:00:07
Performing speech recognition: 100% |#####################################################| Time: 0:02:35
Traceback (most recent call last): |                                                     | ETA:  --:--:--
  File "/usr/local/bin/autosub", line 257, in <module>
    sys.exit(main())
  File "/usr/local/bin/autosub", line 224, in main
    for i, transcript in enumerate(pool.imap(translator, transcripts)):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: 'HTTPError()'. Reason: 'PicklingError("Can't pickle <type 'cStringIO.StringO'>: attribute lookup cStringIO.StringO failed",)'

**Comment by perpi** [comment]
I get this error:

autosub -F srt -S en-US -D en file.mp4 

     Traceback (most recent call last):
     File "/usr/local/bin/autosub", line 257, in <module>
     sys.exit(main())
     File "/usr/local/bin/autosub", line 193, in main
     audio_filename, audio_rate = extract_audio(args.source_path)
     File "/usr/local/bin/autosub", line 103, in extract_audio
     subprocess.check_output(command)
     File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
     process = Popen(stdout=PIPE, *popenargs, **kwargs)
     File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
     errread, errwrite)
     File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
     raise child_exception
     OSError: [Errno 2] No such file or directory

I've installed iy by ‍‍‍‍‍‍‍‍‍‍‍‍‍'pip'

**Comment by flashguy22** [comment]
Same issue here. 
Works like a charm when "-S de-DE -D de" but breaks if "-S de_DE -D en".
Somehow the translation doesn't work sometimes. Half an hour ago I used the same video file and was able to generate an english subtitle from a german video. Ist there some sort of API with limits being used?

autosub -S de-DE -D en video.mp4 
Converting speech regions to FLAC files: 100% |##################################################################################################################| Time: 0:00:01
Performing speech recognition: 100% |############################################################################################################################| Time: 0:00:08
Traceback (most recent call last): |                                                                                                                            | ETA:  --:--:--
  File "/usr/local/bin/autosub", line 258, in <module>
    sys.exit(main())
  File "/usr/local/bin/autosub", line 225, in main
    for i, transcript in enumerate(pool.imap(translator, transcripts)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: 'HTTPError()'. Reason: 'PicklingError("Can't pickle <type 'cStringIO.StringO'>: attribute lookup cStringIO.StringO failed",)'

**Comment by agermanidis** [comment]
Yeah, seems like the Google Translate API is rate-limiting the calls, and perhaps the rate limit got reduced recently. I'm going to look for alternatives for doing the translation.

**Comment by RNabel** [comment]
[Goslate's PyPI page](https://pypi.python.org/pypi/goslate) states that Google introduced a ticketing system, which the developers will not try to circumvent. 

What about adding an additional command line argument to allow the user to specify their own Google Translate API key? Then the [Google Translate python library](https://developers.google.com/api-client-library/python/apis/translate/v2#system-requirements) could be used.

**Comment by agermanidis** [comment]
This should be fixed by @RNabel's changes. An API key for Google Translate is now required.

**Comment by Hitaro** [comment]
May you update README file. I'm not familiar this new approach! What is Google Translate API?

**Comment by RNabel** [comment]
Hey @Hitaro, before the README is updated here a quick summary:

Google's Translate API allows you direct access to Google's translation services through a REST interface. The Translate API charges you 20$ per million characters (~5c per page). To create an API key:

1. Head over to the [Google Cloud console] (console.cloud.google.com/home/dashboard)
0. Create a new project (or use an existing one) - you can select it at the top, the default should be "My First Project".
0.  Head over to the [API manager](https://console.cloud.google.com/apis/api/translate), and enable the API. This gives all code associated the current project the "permission" to access this service.
0. Click on to "Credentials" on the left-hand menu
0. Click on "Create credentials" and select "API key" from the drop down.
0. Select "Server key"
0. Enter an appropriate name, and select "Create".

You can now copy the key and use it in autosub.

**Comment by Hitaro** [comment]
> e Translate API charges you 20$ per million characters

formerly, I did this: uploading my videos into Youtube and then fetching the subtitle by '[Youtube-dl](http://rg3.github.com/youtube-dl/documentation.html)'

**Comment by RNabel** [comment]
Youtube only supports a subset of all languages as input, Bulgarian for example is not supported.

**Comment by emzi** [comment]
May you update README file?! I should also link to this page evrey time I need to introduce this app to my friends!
