### ISSUE TITLE
Does it works without translation api?

### ISSUE THREAD

**Issue by seisdr** [agermanidis/autosub#122]

**Comment by helloworldkr** [comment]
Please explain your problem ...
Caption generation works without translation api
but if  you want translated text then you need translation api
you can also use https://pypi.org/project/googletrans/ for getting translation

**Comment by alanzchen** [comment]
I guess it just has something to do with the default behavior. I ran it with `-S zh-CN` without any `-D` and it asked for API key AFTER converting and uploading. I assumed that by only specifying `-S` it will output the subtitle with the same language. 

It would be much better to check these things before actually doing any work.

**Comment by BingLingGroup** [comment]
> I guess it just has something to do with the default behavior. I ran it with `-S zh-CN` without any `-D` and it asked for API key AFTER converting and uploading. I assumed that by only specifying `-S` it will output the subtitle with the same language.
> 
> It would be much better to check these things before actually doing any work.

只给出-S却要求翻译api key，这是一个已知的逻辑bug，参考 #87 
我[fork的版本](https://github.com/BingLingGroup/autosub/tree/alpha)已经对此以及另一已知问题进行了修复 #136 
至于楼主所问的问题本身而言，具体的解释是speech-to-text api和translation api是两个api，完全可以分开使用。
具体到autosub使用的api如何，可以参考这个问题 #50

**Comment by BingLingGroup** [comment]
Free translation api version [here](https://github.com/BingLingGroup/autosub/releases).

**Comment by helloworldkr** [comment]
@BingLingGroup Please close the issue now since you have made the version as per your requirement

**Comment by BingLingGroup** [comment]
@helloworldkr  I'm not the owner or collaborator of this repo. I can't close it.

**Comment by seisdr** [comment]
I didn't even remember what is this sorry
