### ISSUE TITLE
Auto punctuation feature...

### ISSUE THREAD

**Issue by krishr2d2** [agermanidis/autosub#124]
Does this package support google-speech-api's enable_auto_punctuation feature ?

**Comment by BingLingGroup** [comment]
If you see through the code and find [constants.py](https://github.com/agermanidis/autosub/blob/master/autosub/constants.py), you will find out that api included in this file isn't the latest cloud speech api. https://www.google.com/speech-api/v2/recognize seems an old api website from chrome. These are the docs I could find on github [gillesdemey/google-speech-v2](https://github.com/gillesdemey/google-speech-v2). I don't know if the old api usage is similar to the latest cloud speech api one's.

And from this issue [your api key#1](https://github.com/agermanidis/autosub/issues/1), we can know that it is from chrome.
