### ISSUE TITLE
User in Mainland China cannot use even got VPN ( enable to watch on youtube and use google searching engine)

### ISSUE THREAD

**Issue by yoyo115956** [agermanidis/autosub#174]
**I found that even I got a VPN still cannot use it when I'm in mainland China.** It mentions "Error! You need to have internet connection to use pyTranscriber!". **And I know that somehow it was blocked to get to google, but I can use VPN to search in google engine, even get to youtube.** Please give me a favor for checking this issue.  I'm a user who really loves this app and I really need this function for my video subtitles. 😭

**Comment by deemoprobe** [comment]
+1
