### ISSUE TITLE
Files with spaces will raise an exception

### ISSUE THREAD

**Issue by eightnoteight** [agermanidis/autosub#2]
![screenshot from 2015-07-04 08 48 10](https://cloud.githubusercontent.com/assets/6435796/8506265/77656ff4-2229-11e5-87f4-4e7e02238c00.png)

generating the command everytime or writing a list substitution function would be a good idea,

    cmd = ['ffmpeg', 'filename', ]
    for x, y in kwargs.iteritems():
        cmd[cmd.index(x)] = y

rather than str.format and splitting.
str.format and splitting is also a working idea if you separate the ffmpeg arguments with a unique token(but that is just complicated)

great tool btw...

**Comment by agermanidis** [comment]
Fixed! Thanks for pointing this out. Let me know if you run into any other issues.
