### ISSUE TITLE
No srt output

### ISSUE THREAD

**Issue by songbaoqiang** [agermanidis/autosub#24]
After one hour past, I just get a blank srt file.Why?

**Comment by JohnChinaWu** [comment]
Me too.
<img width="338" alt="screen shot 2016-07-10 at 1 36 57 pm" src="https://cloud.githubusercontent.com/assets/20377340/16711868/691db2cc-46a3-11e6-9d86-a58aabb3d6be.png">

**Comment by DavidYaonanZhu** [comment]
me too

**Comment by DavidYaonanZhu** [comment]
Do this program need to be online? And get access to Google server? 
If it is, I think I know why I get blank files, because in china you can't access Google.

**Comment by DavidYaonanZhu** [comment]
I have just figured the problem by VPN. This program works well!

**Comment by agermanidis** [comment]
Glad you figured it out -- I'll make a note to throw an error if you have no internet connection.
