### ISSUE TITLE
Capitalisation within lines is lost

### ISSUE THREAD

**Issue by peskdale** [agermanidis/autosub#27]
The use of [capitalize()](https://docs.python.org/2/library/string.html#string.capitalize) on each line of the speech API output [here](https://github.com/agermanidis/autosub/blob/master/bin/autosub#L81) causes capital letters in proper nouns and abbreviations to be lost.

For example:
API output: `the city of York is in the UK`
Subtitle: `The city of york is in the uk`

Instead, something along the lines of
```python
line = line['result'][0]['alternative'][0]['transcript']
return line[:1].upper() + line[1:]
```
could be used instead.

**Comment by agermanidis** [comment]
Good catch -- mind submitting a PR? Thanks!
