### ISSUE TITLE
No file or directory

### ISSUE THREAD

**Issue by rahulroxx** [agermanidis/autosub#29]
I made sure that video file "welcome.mp4" is in the directory where I ran 

`autosub welcome.py`

Outputs the error: 

> Traceback (most recent call last):
>   File "/home/rahul/miniconda2/bin/autosub", line 284, in <module>
>     sys.exit(main())
>   File "/home/rahul/miniconda2/bin/autosub", line 210, in main
>     audio_filename, audio_rate = extract_audio(args.source_path)
>   File "/home/rahul/miniconda2/bin/autosub", line 120, in extract_audio
>     subprocess.check_output(command)
>   File "/home/rahul/miniconda2/lib/python2.7/subprocess.py", line 566, in check_output
>     process = Popen(stdout=PIPE, *popenargs, **kwargs)
>   File "/home/rahul/miniconda2/lib/python2.7/subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "/home/rahul/miniconda2/lib/python2.7/subprocess.py", line 1335, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

**Comment by agermanidis** [comment]
Do you have ffmpeg installed?

**Comment by rahulroxx** [comment]
Thanks, @agermanidis
