### ISSUE TITLE
Ubuntu not generating srt files correctly(only 5% accuracy)

### ISSUE THREAD

**Issue by harikrishnantb** [agermanidis/autosub#49]
Hi,
thanks for the great library :+1: 

Installed autosub with python 2.7 in ubuntu 14.04 and using ffmpeg. Autosub is generating subtitle files, but the subtitle files are not accurate, its about only 5% accuracy.

I used the command as 'autosub videofile.mp4'.
Tried this video : https://www.youtube.com/watch?v=Ya6Av7uecbg

and the output is
[President Obama Addresses the Nation on the BP Oil Spill.txt](https://github.com/agermanidis/autosub/files/713028/President.Obama.Addresses.the.Nation.on.the.BP.Oil.Spill.txt)

Do I need to install/setup any additional libraries/plug-ins. Is any specific ffmpeg version needed. Is any machine configurations needed to change.

Please help.

**Comment by kjspring** [comment]
Hilarious subtitle from that video!

I tested the same video using autosub on Ubuntu 16.04. I get less than a 5% error rate. I am using ffmpeg version 2.8.11.

Are you sure you put English as the input for the audio?

**Comment by harikrishnantb** [comment]
Hi,

thanks for your reply. Thanks for the great library.

We got the correct results now. We are using google cloud speech apis now.


Thanks,

Harikrishnan TB
Q*Burst | *www.qburst.com
Skype: harikrishnan.qburst
