### ISSUE TITLE
“python setup.py egg_info” failed with error code 1 when installing autosub

### ISSUE THREAD

**Issue by coolwei1** [agermanidis/autosub#57]
I tried to install [Autosub][1] but it shown error, and I cannot find a solution that work for me.

I already installed ffmpeg that required by Autosub and added path for it.

I also upgraded my setuptools.

    C:\WINDOWS\system32>pip install autosub
    Collecting autosub
      Using cached autosub-0.3.11.tar.gz
    Collecting google-api-python-client>=1.4.2 (from autosub)
      Using cached google_api_python_client-1.6.2-py2.py3-none-any.whl
    Requirement already satisfied: requests>=2.3.0 in c:\program files\python36\lib\site-packages (from autosub)
    Collecting pysrt>=1.0.1 (from autosub)
      Using cached pysrt-1.1.1.tar.gz
    Collecting progressbar>=2.3 (from autosub)
      Using cached progressbar-2.3.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "C:\Users\CHEKWE~1\AppData\Local\Temp\pip-build-4wnmhm6k\progressbar\setup.py", line 5, in <module>
            import progressbar
          File "C:\Users\CHEKWE~1\AppData\Local\Temp\pip-build-4wnmhm6k\progressbar\progressbar\__init__.py", line 59, in <module>
            from progressbar.widgets import *
          File "C:\Users\CHEKWE~1\AppData\Local\Temp\pip-build-4wnmhm6k\progressbar\progressbar\widgets.py", line 121, in <module>
            class FileTransferSpeed(Widget):
          File "c:\program files\python36\lib\abc.py", line 133, in __new__
            cls = super().__new__(mcls, name, bases, namespace)
        ValueError: 'format' in __slots__ conflicts with class variable
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\CHEKWE~1\AppData\Local\Temp\pip-build-4wnmhm6k\progressbar\

I found another answer that said enter `easy_install -U setuptools` but shown error too. (cmd is run as admin)

    C:\WINDOWS\system32>easy_install -U setuptools
    Searching for setuptools
    Reading https://pypi.python.org/simple/setuptools/
    Best match: setuptools 35.0.1
    Processing setuptools-35.0.1-py3.6.egg
    setuptools 35.0.1 is already the active version in easy-install.pth
    Installing easy_install-script.py script to c:\program files\python36\Scripts
    Installing easy_install.exe script to c:\program files\python36\Scripts
    error: [WinError 5] Access is denied: 'c:\\program files\\python36\\Scripts\\easy_install.exe'

Any help would be appreciated.

  [1]: https://github.com/agermanidis/autosub

**Comment by serranoarevalo** [comment]
How did you fix this?
