### ISSUE TITLE
Exception: Dependency not found: ffmpeg

### ISSUE THREAD

**Issue by c1097198892** [agermanidis/autosub#94]
There are some problems happened when I ran the command. I actually added the path of ffmpeg into the PATH and the command "ffmpeg -version" can return a correct result.

(Subgen) D:\SystemFiles\Videos>autosub 01.mp4
ffmpeg: Executable not found on machine.
Traceback (most recent call last):
  File "F:\Anaconda3\envs\Subgen\Scripts\autosub-script.py", line 11, in <module>
    load_entry_point('autosub==0.3.13', 'console_scripts', 'autosub')()
  File "F:\Anaconda3\envs\Subgen\lib\site-packages\autosub-0.3.13-py3.6.egg\autosub\__init__.py", line 257, in main
  File "F:\Anaconda3\envs\Subgen\lib\site-packages\autosub-0.3.13-py3.6.egg\autosub\__init__.py", line 275, in generate_subtitles
  File "F:\Anaconda3\envs\Subgen\lib\site-packages\autosub-0.3.13-py3.6.egg\autosub\__init__.py", line 148, in extract_audio
Exception: Dependency not found: ffmpeg

and ffmpeg:

(Subgen) D:\SystemFiles\Documents\Toys>ffmpeg -version
ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7.3.0 (GCC)

Environment:
Windows10 1709
Anaconda3
Python 3.6.5

**Comment by c1097198892** [comment]
It works normally by installing autosub with: https://github.com/agermanidis/autosub/issues/31

**Comment by c1097198892** [comment]
It works normally by installing autosub with: https://github.com/agermanidis/autosub/issues/31

**Comment by qijianjun** [comment]
Just comment out the following code in Python27\Scripts\autosub_app.py:
```
    if not which("ffmpeg"):
        print "ffmpeg: Executable not found on machine."
        raise Exception("Dependency not found: ffmpeg")

```

**Comment by waqasaslam5550** [comment]
hey @Asuka109  i m facing same issue can u plz tell me how you solved it?

**Comment by ryotutui** [comment]
I got the same issue and I couldn't find "Python27\Scripts\autosub_app.py" in my environment but commented out the code mentioned above in "Python27\Lib\site-packages\autosub\__init__.py" and could solve the issue.

**Comment by ryotutui** [comment]
Sorry the correct path is "Python27\Lib\site-packages\autosub\_init_.py"
